### ISSUE TITLE
Global config not used

### ISSUE THREAD

**Issue by dgsiegel** [bnomei/kirby3-qrcode#13]
I added this to my kirby config:

```
<?php

return [
    // other options
    'bnomei.qrcode.field' => [
        'size' => 128,
        'margin' => 0,
    ],
];
```

In my template (e.g. `site/templates/default.qr.php`) I then use:

```
$page->qrcode()->download(
    $page->slug() . '.png'
);
```

I'd expect the above settings to be applied, but in fact they are not.

**Comment by bnomei** [comment]
this is actually intended since the `field` option should configure the display of all qrcodes inside the panel views but not in any frontend code (like templates). i will make that more clear in the readme.

```php
<?php

return [
    // other options
    'bnomei.qrcode.field' => [ // <--- panel
        'size' => 128,
        'margin' => 0,
    ],
    'dgsiegel.qrcode' => [ // <-- example for your frontend
        'size' => 128,
        'margin' => 0,
    ],
];
```

in template
```php
$page->qrcode(option('dgsiegel.qrcode'))->download(
    $page->slug() . '.png'
);
```

**Comment by dgsiegel** [comment]
Makes sense, thanks.
