### ISSUE TITLE
PDF generation not possible

### ISSUE THREAD

**Issue by dgsiegel** [bnomei/kirby3-qrcode#16]
Using

```
$page->qrcode()->download(
  $page->slug() . ".pdf"
);
```

I get the following error: 

`site/plugins/kirby3-qrcode/vendor/endroid/qr-code/src/Writer/PdfWriter.php: Unable to find FPDF: check your installation`

Would it be possible to add FPDF as a dependency to composer.json?

**Comment by bnomei** [comment]
composer merges all sources. you should be able to run

```bash
composer require setasign/fpdf:^1.8
```

an have that lib available then.

i am not in favor for adding pdf generation by default since i want to keep the plugins as small as possible and fpdf is a big lib.
