### ISSUE TITLE
Custom css class for image

### ISSUE THREAD

**Issue by squareclouds** [bnomei/kirby3-qrcode#25]
hello and thank you for the great plugin. i was wondering if a custom css class could be added somehow to the img tag that is generated in the front-end via

```php
<?= $page->qrcode()->html(
        $page->slug() . '.png' // image format detected from extension
    ); ?>
```

or maybe even better a set of attributes in case the img needs something else.

**Comment by bnomei** [comment]
that should already be possible.
https://github.com/bnomei/kirby3-qrcode/blob/2fc2a2ace80a1de4506c4e7b4a472da043307d8e/classes/QRCode.php#L62

```php
<?= $page->qrcode()->html(
        $page->slug() . '.png',
        ['class' => 'myclass']
    ); ?>
```

**Comment by squareclouds** [comment]
perfect! thank you very much :)
