### ISSUE TITLE
Setting colors throws an error

### ISSUE THREAD

**Issue by trych** [bnomei/kirby3-qrcode#31]
Hi there,

thanks for the plugin!
When I try to set the fg and bg colors as described in the README:

```php
<?php

return [
    // other options...
    
    // set values for qrcode inside the panel
    'bnomei.qrcode.field' => [
        'foregroundColor' => new \Endroid\QrCode\Color\Color(126, 154, 191),
        'backgroundColor' => new \Endroid\QrCode\Color\Color(239, 239, 239),
    ],
];
```

I get a server error. As this is an error in the config file itself, I don't quite know hot to debug this (debug is set to true, but as it does not finish evaluating the config file it still does not debug).

Setting other properties (size, margin etc.) works.

**Comment by bnomei** [comment]
how did you install the plugin? via zip or composer? it seems too work with composer install.

can you try with this?

```php
<?php

require_once __DIR__ . '/../plugins/kirby3-qrcode/vendor/endroid/qr-code/src/Color/ColorInterface.php';
require_once __DIR__ . '/../plugins/kirby3-qrcode/vendor/endroid/qr-code/src/Color/Color.php';

return [
    'debug' => true,

    'bnomei.qrcode.field' => [
        'foregroundColor' => new \Endroid\QrCode\Color\Color(126, 154, 191),
        'backgroundColor' => new \Endroid\QrCode\Color\Color(239, 239, 239),
        'size' => 128,
        'margin' => 0,
    ],
];
```

**Comment by trych** [comment]
Installed it as git submodule. I added the two `require_once` lines as you suggested, still getting the same issue unfortunately.

**Comment by bnomei** [comment]
I'm closing this issue since I can help install it as a git submodule. Please try Composer, which makes handling class dependencies in PHP much easier
