### ISSUE TITLE
add save as file helper

### ISSUE THREAD

**Issue by bnomei** [bnomei/kirby3-qrcode#32]
https://forum.getkirby.com/t/plugin-qr-code-field-and-page-method/6798/4

@trych

**Comment by bnomei** [comment]
done in 2.1.0

**Comment by bnomei** [comment]
https://github.com/bnomei/kirby3-qrcode#save-as-file-in-page-object

**Comment by trych** [comment]
Wow, thank you so much! 🙏 Will give this a try as soon as I can.

**Comment by trych** [comment]
Just gave this a test, works great. Thanks again!
