### ISSUE TITLE
Too few arguments to function Bnomei\QRCode::html()

### ISSUE THREAD

**Issue by afbora** [bnomei/kirby3-qrcode#36]
I tried to use sample in readme

````php
$qrcodeObject = new \Bnomei\QRCode([
    'Text' => 'https://github.com/bnomei/kirby3-qrcode',
]);
echo $qrcodeObject->html();
````
And I'm getting following error:

> Too few arguments to function Bnomei\QRCode::html(), 0 passed in \site\templates\home.php on line 6 and at least 1 expected

![screen-capture-1747-Kirby CMS Debugger-plugins test](https://github.com/bnomei/kirby3-qrcode/assets/3393422/87adbbb4-774d-4f0a-9de5-052bd8535757)

**Comment by distantnative** [comment]
@afbora don't think this is a Kirby 4 bug but just incorrect docs - this should also fail in Kirby 3 as https://github.com/bnomei/kirby3-qrcode/blob/master/classes/QRCode.php#L68 requires the `$name` parameter

**Comment by afbora** [comment]
I know. I added it to the K4 list on the principle that what doesn't work in K3 doesn't work in K4 😅
